### ISSUE TITLE
Tidy Manifest

### ISSUE THREAD

**Issue by adam2392** [adam2392/iclabel-python#20]
For the `MANIFEST.in`, we can fix it in a follow-up. It needs more clean-up than just this `.txt`, and also do we include the data for the test files or not?

Let me know if the previous comment answers your question for the CAR issue.

_Originally posted by @mscheltienne in https://github.com/jacobf18/iclabel-python/issues/18#issuecomment-1111113074_

We should tighten up the MANIFEST file to remove any data files, and include only the necessary python and text files for a distribution.

**Comment by mscheltienne** [comment]
To be done after `iclabel` submodule is added since it will impact paths. c.f. #21
